services:
  mysql:
    image: mysql:8.0
    container_name: off_mysql_db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: off_datamart
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    command: --innodb-redo-log-capacity=1G
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 10

  etl:
    build: .
    container_name: off_etl
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./en.openfoodfacts.org.products.csv:/app/en.openfoodfacts.org.products.csv:ro
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=off_datamart
      - DB_USER=root
      - DB_PASSWORD=password

volumes:
  mysql_data:
